repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v3.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.8.4"
    hooks:
      - id: flake8
        additional_dependencies:
          - isort==4.3.21
          - "wemake-python-styleguide==0.14.1"
        args: ["--config=setup.cfg"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
        exclude: ^docs|^tests

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
        files: .yml$|.yaml$|.json$

  - repo: local
    hooks:
      - id: pytest
        name: run tests
        entry: poetry run pytest -v
        pass_filenames: false
        language: system
        always_run: true
        types: [python]
        stages: [push]
