name: CI

on: ["push", "pull_request"]

jobs:
  tests-legacy-pandas:
    runs-on: "ubuntu-latest"
    env:
      USING_COVERAGE: "3.7"

    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8"]
        pandas: ["0.25.3"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python }}"

      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade coverage[toml] virtualenv tox tox-gh-actions

      - name: "Run tox targets for py${{ matrix.python }}-pandas${{ matrix.pandas}}"
        run: "python -m tox -e py${{ matrix.python }}-pandas${{ matrix.pandas }}"

      - name: "Generate XML coverage"
        if: env.USING_COVERAGE ==  matrix.python
        run: |
          set -xe
          python -m coverage xml

      - name: "Upload coverage to Codecov"
        if: env.USING_COVERAGE ==  matrix.python
        uses: "codecov/codecov-action@v1"
        with:
          fail_ci_if_error: true

  tests:
    runs-on: "ubuntu-latest"
    env:
      USING_COVERAGE: "3.8"

    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9"]
        pandas: ["latest"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python }}"

      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade coverage[toml] virtualenv tox tox-gh-actions

      - name: "Run tox targets for py${{ matrix.python }}-pandas${{ matrix.pandas}}"
        run: "python -m tox -e py${{ matrix.python }}-pandas${{ matrix.pandas }}"

      - name: "Upload coverage to Codecov"
        if: env.USING_COVERAGE ==  matrix.python
        run: |
          set -xe
          python -m coverage xml

      - name: "Upload coverage to Codecov"
        if: env.USING_COVERAGE ==  matrix.python
        uses: "codecov/codecov-action@v1"
        with:
          fail_ci_if_error: true

  others:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        toxenv: ["lint", "docs"]
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.8"
      - name: "Install tox"
        run: "python -m pip install tox"
      - name: "${{ matrix.toxenv }}"
        run: "python -m tox -e ${{ matrix.toxenv }}"

  package:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: 3.8
      - name: "Install poetry and tox"
        run: "python -m pip install poetry tox"
      - name: "Build & verify package"
        run: "python -m tox -e package"
