name: Tests

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install tox
        run: python -m pip install tox
      - name: Run tox
        run: python -m tox -e lint

  tests:
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 4
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        toxenv:
          - py38-pandas1
          - py38-pandas0251
          - py37-pandas1
          - py37-pandas0251
          - py36-pandas1
          - py36-pandas0251

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
        if: startsWith(matrix.toxenv, 'py36')
      - name: Setup Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
        if: startsWith(matrix.toxenv, 'py37')
      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
        if: startsWith(matrix.toxenv, 'py38')
      - name: Install tox and any other packages
        run: python -m pip install tox
      - name: Run tox
        run: python -m tox -e ${{ matrix.toxenv }}

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install tox and any other packages
        run: python -m pip install tox
      - name: Run tox
        run: python -m tox -e docs